name: 'dbt_bda'
version: '1.0.0'
config-version: 2

profile: 'dbt-bda-snowflake-profile'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  dbt_bda:
    bda:
      +materialized: view
